---
- name: enabled asis
  apache2_module: name=asis state=present
  notify:
    - restart apache2

- name: enabled authn_default
  apache2_module: name=authn_default state=present
  notify:
    - restart apache2

- name: enabled cache
  apache2_module: name=cache state=present
  notify:
    - restart apache2

- name: enabled dav
  apache2_module: name=dav state=present
  notify:
    - restart apache2

- name: enabled disk_cache
  apache2_module: name=disk_cache state=present
  notify:
    - restart apache2

- name: enabled dav_fs
  apache2_module: name=dav_fs state=present
  notify:
    - restart apache2

- name: enabled dav_lock
  apache2_module: name=dav_lock state=present
  notify:
    - restart apache2

- name: enabled expires
  apache2_module: name=expires state=present
  notify:
    - restart apache2

- name: enabled filter
  apache2_module: name=filter state=present
  notify:
    - restart apache2

- name: enabled headers
  apache2_module: name=headers state=present
  notify:
    - restart apache2

- name: enabled include
  apache2_module: name=include state=present
  notify:
    - restart apache2

- name: enabled proxy
  apache2_module: name=proxy state=present
  notify:
    - restart apache2

- name: enabled proxy_connect
  apache2_module: name=proxy_connect state=present
  notify:
    - restart apache2

- name: enabled proxy_http
  apache2_module: name=proxy_http state=present
  notify:
    - restart apache2

- name: enabled rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2

- name: enabled vhost_alias
  apache2_module: name=vhost_alias state=present
  notify:
    - restart apache2
